import { useEffect, useMemo, useState } from 'react'

type Nav = 'Home' | 'Operations' | 'Assets' | 'Work' | 'Agents' | 'Research' | 'Validation' | 'Decisions' | 'History'
type RunState = 'READY_NOT_DISPATCHED' | 'DISPATCHED_AWAITING_ACK' | 'RUNNING_CONFIRMED' | 'BLOCKED' | 'STALE_UNKNOWN' | 'COMPLETED_PASS' | 'COMPLETED_FAIL' | 'COMPLETED_WITH_FINDINGS'
type StatusPayload = { project: string; short_name: string; aaa_role: string; canonical_authority: string; llm_required_for_control_plane: boolean; current_state: { version: string | null; status: string | null; identity: { path: string; sha256: string; byte_size: number } } }
type DiscrepancyPayload = { status: 'MATCH' | 'MISMATCH' | 'STALE' | 'UNKNOWN'; projection_scope: string; event_ledger: { latest_event_id: string | null }; comparisons: { key: string; status: 'MATCH' | 'MISMATCH' | 'UNKNOWN' }[] }
type RunPayload = { run_id: string; process_id: string; responsible_persona: string; state: RunState; effective_state: RunState; exact_base_commit: string; branch: string; last_heartbeat_at: string | null }
type PersonaPayload = { persona: string; state: RunState | 'IDLE_OR_UNREGISTERED'; run_id: string | null; process_id: string | null }
type WorkerPayload = { worker_id: string; worker_type: string; runtime_version: string; host_identity: string; enabled: boolean; last_seen_at: string | null; capabilities: string[]; authorized_personas: string[] }
type TaskPayload = { task_id: string; run_id: string; execution_profile_id: string; required_persona: string; state: string; effective_task_state: string; claimed_by: string | null; lease_epoch: number | null; acknowledged_at_db: string | null; started_at_db: string | null; last_heartbeat_at: string | null; lease_expires_at: string | null }

const navItems: Nav[] = ['Home', 'Operations', 'Assets', 'Work', 'Agents', 'Research', 'Validation', 'Decisions', 'History']
const API = 'http://127.0.0.1:8765/api/aaa'
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section style={{ background: '#111827', border: '1px solid #263244', borderRadius: 12, padding: 18 }}><h3 style={{ margin: '0 0 12px', fontSize: 15, color: '#d1d5db' }}>{title}</h3>{children}</section> }
function Pill({ children }: { children: React.ReactNode }) { return <span style={{ background: '#1f2937', borderRadius: 999, padding: '7px 11px', color: '#bfdbfe' }}>{children}</span> }
function statusColor(value: string) { if (value === 'MATCH' || value === 'COMPLETED_PASS' || value === 'RUNNING_CONFIRMED' || value === 'RUNNING' || value === 'TERMINAL') return '#86efac'; if (value === 'UNKNOWN' || value === 'READY_NOT_DISPATCHED' || value === 'DISPATCHED_AWAITING_ACK' || value === 'IDLE_OR_UNREGISTERED' || value === 'AVAILABLE' || value === 'CLAIMED' || value === 'ACKNOWLEDGED') return '#fcd34d'; if (value === 'COMPLETED_WITH_FINDINGS' || value === 'STALE_UNKNOWN') return '#fdba74'; return '#fca5a5' }
function shortPersona(value: string) { if (value === 'SEMI-CONTROL-ARCHITECT') return 'Control Architect'; if (value === 'SEMI-MODEL-VALIDATION-DESIGN-ARCHITECT') return 'Model Validation / Design'; if (value === 'SEMI-RESEARCH-ORCHESTRATOR') return 'Research Orchestrator'; if (value === 'SEMI-VALIDATION-AUDITOR') return 'Validation Auditor'; return value }

export default function App() {
  const [active, setActive] = useState<Nav>('Home'); const [status, setStatus] = useState<StatusPayload | null>(null); const [discrepancy, setDiscrepancy] = useState<DiscrepancyPayload | null>(null); const [workCount, setWorkCount] = useState<number | null>(null); const [gates, setGates] = useState<string[]>([]); const [runs, setRuns] = useState<RunPayload[]>([]); const [personas, setPersonas] = useState<PersonaPayload[]>([]); const [workers, setWorkers] = useState<WorkerPayload[]>([]); const [tasks, setTasks] = useState<TaskPayload[]>([]); const [executionProjectionConnected, setExecutionProjectionConnected] = useState(false); const [apiState, setApiState] = useState<'LOADING' | 'ONLINE' | 'OFFLINE'>('LOADING')
  useEffect(() => { const load = async () => { try { const responses = await Promise.all([fetch(`${API}/status`, { cache: 'no-store' }), fetch(`${API}/work`, { cache: 'no-store' }), fetch(`${API}/gates`, { cache: 'no-store' }), fetch(`${API}/state/compare`, { cache: 'no-store' }), fetch(`${API}/runs`, { cache: 'no-store' }), fetch(`${API}/personas`, { cache: 'no-store' }), fetch(`${API}/workers`, { cache: 'no-store' }), fetch(`${API}/tasks`, { cache: 'no-store' })]); if (responses.some((response) => !response.ok)) throw new Error('AAA_API_READ_FAILED'); const [statusPayload, workPayload, gatePayload, discrepancyPayload, runPayload, personaPayload, workerPayload, taskPayload] = await Promise.all(responses.map((response) => response.json())); setStatus(statusPayload as StatusPayload); setWorkCount((workPayload as { items: unknown[] }).items.length); setGates((gatePayload as { items: string[] }).items); setDiscrepancy(discrepancyPayload as DiscrepancyPayload); setRuns((runPayload as { items: RunPayload[] }).items); setPersonas((personaPayload as { items: PersonaPayload[] }).items); setWorkers((workerPayload as { items: WorkerPayload[] }).items); setTasks((taskPayload as { items: TaskPayload[] }).items); setExecutionProjectionConnected(Boolean((workerPayload as { postgres_projection_connected?: boolean }).postgres_projection_connected)); setApiState('ONLINE') } catch { setApiState('OFFLINE') } }; void load() }, [])

  const content = useMemo(() => {
    if (active === 'Operations') return <div style={{ display: 'grid', gap: 16 }}>
      <Card title="T19 worker execution plane"><div style={{ marginBottom: 10, color: executionProjectionConnected ? '#86efac' : '#fcd34d', fontSize: 12 }}>PostgreSQL execution projection: {executionProjectionConnected ? 'CONNECTED' : 'NOT CONNECTED · no worker liveness inferred'}</div><div style={{ display: 'grid', gap: 8 }}>{workers.map((worker) => <div key={worker.worker_id} style={{ borderBottom: '1px solid #1f2937', padding: '9px 0' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong>{worker.worker_id}</strong><strong style={{ color: worker.enabled ? '#86efac' : '#fca5a5' }}>{worker.enabled ? 'ENABLED' : 'DISABLED'}</strong></div><div style={{ color: '#94a3b8', fontSize: 12, marginTop: 4 }}>{worker.worker_type} · {worker.runtime_version} · last seen {worker.last_seen_at ?? 'never'}</div></div>)}{workers.length === 0 && <span style={{ color: '#9ca3af' }}>No connected worker evidence.</span>}</div></Card>
      <Card title="T19 execution tasks"><div style={{ display: 'grid', gap: 8 }}>{tasks.map((task) => <div key={task.task_id} style={{ border: '1px solid #1f2937', borderRadius: 10, padding: 12 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><strong>{task.task_id}</strong><strong style={{ color: statusColor(task.effective_task_state) }}>{task.effective_task_state}</strong></div><div style={{ color: '#94a3b8', fontSize: 12, marginTop: 5 }}>{task.run_id} · {shortPersona(task.required_persona)}</div><div style={{ color: '#64748b', fontSize: 11, marginTop: 4 }}>worker {task.claimed_by ?? 'unclaimed'} · lease {task.lease_epoch ?? 'none'} · heartbeat {task.last_heartbeat_at ?? 'none'}</div></div>)}{tasks.length === 0 && <span style={{ color: '#9ca3af' }}>No executable task projection connected.</span>}</div></Card>
      <Card title="Persona operations"><div style={{ display: 'grid', gap: 8 }}>{personas.map((row) => <div key={row.persona} style={{ display: 'flex', justifyContent: 'space-between', padding: '9px 0', borderBottom: '1px solid #1f2937' }}><span>{shortPersona(row.persona)}</span><strong style={{ color: statusColor(row.state) }}>{row.state}</strong></div>)}</div></Card>
      <Card title="Registered execution Runs"><div style={{ display: 'grid', gap: 8 }}>{runs.map((run) => <div key={run.run_id} style={{ border: '1px solid #1f2937', borderRadius: 10, padding: 12 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong>{run.run_id}</strong><strong style={{ color: statusColor(run.effective_state) }}>{run.effective_state}</strong></div><div style={{ color: '#64748b', fontSize: 11, marginTop: 5 }}>{run.process_id} · heartbeat {run.last_heartbeat_at ?? 'none'}</div></div>)}</div></Card>
    </div>
    if (active === 'Validation') return <div style={{ display: 'grid', gap: 16 }}><Card title="Shadow discrepancy"><strong style={{ color: statusColor(discrepancy?.status ?? 'UNKNOWN') }}>{discrepancy?.status ?? 'UNAVAILABLE'}</strong></Card><Card title="Anchor comparisons"><div style={{ display: 'grid', gap: 8 }}>{discrepancy?.comparisons.map((row) => <div key={row.key} style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #1f2937', padding: '8px 0' }}><span>{row.key}</span><strong style={{ color: statusColor(row.status) }}>{row.status}</strong></div>)}</div></Card></div>
    if (active !== 'Home') return <Card title={active}><p style={{ margin: 0, color: '#9ca3af' }}>Deterministic read-only view. Mutation surfaces remain disabled in Owner Console.</p></Card>
    const runningCount = runs.filter((run) => run.effective_state === 'RUNNING_CONFIRMED').length; const liveWorkerCount = workers.filter((worker) => worker.enabled && worker.last_seen_at).length
    return <div style={{ display: 'grid', gap: 16 }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 16 }}><Card title="Current State"><strong>{status?.current_state.version ?? 'UNAVAILABLE'}</strong><div style={{ marginTop: 8, color: '#93c5fd' }}>{status?.aaa_role ?? 'SHADOW_NONAUTHORITATIVE'}</div></Card><Card title="Runs"><strong style={{ color: '#86efac' }}>{runningCount} RUNNING</strong><div style={{ marginTop: 8, color: '#9ca3af' }}>{runs.length} registered</div></Card><Card title="T19 Workers"><strong style={{ color: executionProjectionConnected ? '#86efac' : '#fcd34d' }}>{liveWorkerCount} observed</strong><div style={{ marginTop: 8, color: '#9ca3af' }}>{executionProjectionConnected ? 'PostgreSQL projection connected' : 'No liveness inferred'}</div></Card><Card title="Shadow State Match"><strong style={{ color: statusColor(discrepancy?.status ?? 'UNKNOWN') }}>{discrepancy?.status ?? 'UNAVAILABLE'}</strong></Card><Card title="Work Orders"><strong>{workCount ?? '—'}</strong><span style={{ color: '#9ca3af' }}> versioned records</span></Card><Card title="Canonical Write"><strong style={{ color: '#fca5a5' }}>PROHIBITED</strong></Card></div><Card title="Control status"><div style={{ color: '#d1d5db' }}>{status?.current_state.status ?? 'READ_ONLY_API_NOT_CONNECTED'}</div></Card><Card title="Validation gates"><div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>{gates.length > 0 ? gates.map((gate) => <Pill key={gate}>{gate}</Pill>) : <span style={{ color: '#9ca3af' }}>No gate data loaded.</span>}</div></Card></div>
  }, [active, discrepancy, executionProjectionConnected, gates, personas, runs, status, tasks, workCount, workers])

  return <div style={{ minHeight: '100vh', background: '#0b1020', color: '#f9fafb', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif' }}><header style={{ padding: '20px 28px', borderBottom: '1px solid #1f2937', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><div style={{ fontWeight: 800, fontSize: 22 }}>Asset Agent ASA</div><div style={{ color: '#64748b', fontSize: 13 }}>AAA Owner Console · deterministic-first</div></div><div style={{ display: 'flex', gap: 8 }}><span style={{ fontSize: 12, padding: '6px 10px', border: '1px solid #334155', borderRadius: 999, color: apiState === 'ONLINE' ? '#86efac' : '#fca5a5' }}>API {apiState}</span><span style={{ fontSize: 12, padding: '6px 10px', border: '1px solid #334155', borderRadius: 999, color: '#cbd5e1' }}>SHADOW / READ-ONLY</span></div></header><div style={{ display: 'grid', gridTemplateColumns: '220px minmax(0, 1fr)', minHeight: 'calc(100vh - 82px)' }}><nav style={{ borderRight: '1px solid #1f2937', padding: 16 }}>{navItems.map((item) => <button key={item} type="button" onClick={() => setActive(item)} style={{ width: '100%', textAlign: 'left', marginBottom: 5, padding: '10px 12px', borderRadius: 8, border: 'none', cursor: 'pointer', color: active === item ? '#fff' : '#94a3b8', background: active === item ? '#1e293b' : 'transparent', fontWeight: active === item ? 700 : 500 }}>{item}</button>)}</nav><main style={{ padding: 28, maxWidth: 1200, width: '100%', boxSizing: 'border-box' }}><div style={{ marginBottom: 20 }}><h1 style={{ margin: 0, fontSize: 26 }}>{active}</h1><p style={{ color: '#64748b', marginTop: 6 }}>Owner-visible persistent state without inferring execution from chat activity.</p></div>{content}</main></div></div>
}
